apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "milk-api-manager.fullname" . }}-backend
  labels:
    app: milk-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: milk-backend
  template:
    metadata:
      labels:
        app: milk-backend
      annotations:
        vault.hashicorp.com/agent-inject: "{{ .Values.backend.vault.enabled }}"
        vault.hashicorp.com/role: "{{ .Values.backend.vault.role }}"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/milk-api/config"
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.backend.env.ASPNETCORE_ENVIRONMENT }}
            - name: VAULT_ADDR
              value: {{ .Values.backend.vault.address }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "milk-api-manager.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: milk-backend
