apiVersion: v2
name: milk-api-manager
description: A production-grade Helm Chart for Milk API Manager System
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: apisix
    version: 2.11.0
    repository: https://charts.apiseven.com
  - name: etcd
    version: 9.7.3
    repository: https://charts.bitnami.com/bitnami
